name: docker-build-httpbin

on:
  pull_request:
    branches:
      - "*"

  push:
    branches:
      - "*"


jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go 1.17
        id: go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      -
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Prepare Host
        run: |
          sudo apt-get -qq update || true
          sudo apt-get install -y pigz
          curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.17.0/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Build images
        env:
          ARCH: amd64
        run: |
          echo "building images..."
          cd images/httpbin; pwd; ls
          PLATFORMS=linux/amd64 make build